server {
    listen 80;
    server_name localhost;

    root /var/www/backend/app/public;
    index index.php;

    # быстрая проверка nginx
    location = /health {
        return 200 "ok\n";
        add_header Content-Type text/plain;
    }

    # Symfony: сначала пробуем отдать файл, иначе на index.php
    location / {
        try_files $uri /index.php$is_args$args;
    }

    # Обработка PHP через php-fpm
    location ~ ^/index\.php(/|$) {
        fastcgi_pass php:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;

        internal;
    }

    # Запрещаем прямой доступ к *.php кроме index.php
    location ~ \.php$ {
        return 404;
    }
}