nelmio_api_doc:
  documentation:
    info:
      title: RealtimeChat API
      description: Messenger REST API
      version: 1.0.0
    components:
      securitySchemes:
        bearerAuth:
          type: http
          scheme: bearer
          bearerFormat: JWT
    security:
      - bearerAuth: []
  areas:
    default:
      path_patterns:
        - ^/api(?!/doc$)
